#ifndef TRANSPORT_CONFIG_H
#define TRANSPORT_CONFIG_H

#define WINDOW_SIZE  500
#define DATAGRAM_LEN 1000
#define RESPONSE_WAIT  500000000 //ns
#define RESEND_TIME  1 // s
#define DATAGRAM_OFFSET 7 // "DATA" + 2 spaces + "\n"

#endif //TRANSPORT_CONFIG_H
