DROP TABLE IF EXISTS num1
DROP TABLE IF EXISTS num2


CREATE TABLE num1(num int)
CREATE TABLE num2(num int)


INSERT INTO num1 VALUES(1)
INSERT INTO num1 VALUES(5)
INSERT INTO num1 VALUES(12)



INSERT INTO num2 VALUES(14)
INSERT INTO num2 VALUES(51)
INSERT INTO num2 VALUES(122)